# Generated by Django 2.0 on 2018-01-23 07:41

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('reg_time', models.DateTimeField(auto_now_add=True, help_text='registered')),
                ('user_pwd', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('slug_title', models.SlugField(unique=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, help_text='data published')),
                ('update_date_time', models.DateTimeField(auto_now=True, help_text='data updated')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to=blog.models.image_upload_to)),
                ('blog_content', models.TextField()),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
            ],
        ),
    ]
