# Generated by Django 2.0 on 2018-01-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user_pwd',
        ),
    ]
