# Generated by Django 2.0 on 2018-01-17 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180117_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='reg_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='registered'),
        ),
    ]
