# Generated by Django 2.0 on 2018-01-23 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180117_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_time',
        ),
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='data published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True, help_text='data updated'),
        ),
        migrations.AlterField(
            model_name='author',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True, help_text='registered'),
        ),
    ]
