# Generated by Django 2.0 on 2018-01-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180123_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
